Update cloud_image_health_check.yml

diff --git a/.github/workflows/cloud_image_health_check.yml b/.github/workflows/cloud_image_health_check.yml
--- a/.github/workflows/cloud_image_health_check.yml
+++ b/.github/workflows/cloud_image_health_check.yml
@@ -62,3 +62,9 @@ jobs:
               Please check the [Actions tab](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for the full report.`,
               labels: ['bad-link']
             })
+
+      - name: Fail workflow
+        if: env.FAILURES_FOUND == 'true'
+        run: |
+          echo "failing workflow due to broken URL"
+          exit 1
